# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-12 15:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='userproject',
            name='status',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='usertask',
            name='consented',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='usertask',
            name='status',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
