# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-05 15:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_externalsystem_userexternalaccount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userexternalaccount',
            name='external_user_id_type',
        ),
        migrations.AddField(
            model_name='externalsystem',
            name='external_user_id_type',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
