# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-17 10:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userexternalaccount',
            name='user',
        ),
    ]
