# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-17 10:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_remove_userexternalaccount_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userexternalaccount',
            name='user',
            field=models.ForeignKey(default='8e385316-5827-4c72-8d4b-af5c57ff4679', on_delete=django.db.models.deletion.CASCADE, to='projects.User'),
            preserve_default=False,
        ),
    ]
