# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-17 10:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_projecttask'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertask',
            name='task',
        ),
        migrations.AddField(
            model_name='usertask',
            name='project_task',
            field=models.ForeignKey(default='8e385316-5827-4c72-8d4b-af5c57ff4679', on_delete=django.db.models.deletion.CASCADE, to='projects.ProjectTask'),
            preserve_default=False,
        ),
    ]
