# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-28 14:18
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_auto_20180817_1113'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntityUpdate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('entity_name', models.CharField(max_length=50)),
                ('entity_id', models.UUIDField(editable=False)),
                ('json_patch', models.CharField(editable=False, max_length=2000)),
                ('json_reverse_patch', models.CharField(editable=False, max_length=2000)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
