# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-19 11:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_entityupdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_address_verified',
            field=models.BooleanField(default=False),
        ),
    ]
