# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-19 15:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0015_user_email_address_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(blank=True, choices=[('planned', 'Planned'), ('active', 'Active'), ('complete', 'Complete')], max_length=12, null=True),
        ),
    ]
