# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-19 17:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0016_auto_20181019_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projecttask',
            name='status',
            field=models.CharField(blank=True, choices=[('planned', 'Planned'), ('active', 'Active'), ('complete', 'Complete')], max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='usertask',
            name='status',
            field=models.CharField(blank=True, choices=[('active', 'Active'), ('complete', 'Complete')], max_length=12, null=True),
        ),
    ]
