# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-24 14:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0020_auto_20181022_1432'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='website_highlight',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='projecttask',
            name='website_highlight',
            field=models.BooleanField(default=False),
        ),
    ]
