# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-24 15:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0022_auto_20181024_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(blank=True, choices=[('planned', 'Planned'), ('testing', 'Testing'), ('active', 'Active'), ('complete', 'Complete')], max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='projecttask',
            name='signup_status',
            field=models.CharField(blank=True, choices=[('not-open', 'Not yet open'), ('open', 'Open'), ('closed', 'Closed')], max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='projecttask',
            name='status',
            field=models.CharField(blank=True, choices=[('planned', 'Planned'), ('testing', 'Testing'), ('active', 'Active'), ('complete', 'Complete')], max_length=12, null=True),
        ),
    ]
