# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-24 15:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0023_auto_20181024_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('planned', 'Planned'), ('testing', 'Testing'), ('active', 'Active'), ('complete', 'Complete')], default='planned', max_length=12),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='visibility',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Private')], default='public', max_length=12),
            preserve_default=False,
        ),
    ]
