# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-29 15:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0026_auto_20181025_1125'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_verification_expiry',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='email_verification_token',
            field=models.UUIDField(editable=False, null=True),
        ),
    ]
