# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-29 15:46
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0027_auto_20181029_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email_verification_token',
            field=models.UUIDField(default=uuid.UUID('79bc06a0-249e-4463-a381-4bc40bf4d455'), editable=False, null=True),
        ),
    ]
