# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-08 09:21
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0029_auto_20181107_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='projecttask',
            name='external_task_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email_verification_token',
            field=models.UUIDField(default=uuid.UUID('67a541ad-6703-4c3e-b1fc-6c9f8be8c532'), editable=False, null=True),
        ),
    ]
