# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-12 16:49
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0031_auto_20181212_1634'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projecttask',
            old_name='external_system_id',
            new_name='external_system',
        ),
        migrations.AlterField(
            model_name='user',
            name='email_verification_token',
            field=models.UUIDField(default=uuid.UUID('1a5c1f46-4e15-4cbd-8650-37cdacb57fdf'), editable=False, null=True),
        ),
    ]
