# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-14 11:59
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0032_auto_20181212_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email_verification_token',
            field=models.UUIDField(default=uuid.UUID('833b7482-85ea-471a-9188-f9bad127b69a'), editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='userexternalaccount',
            name='external_user_id',
            field=models.CharField(blank=True, choices=[('active', 'Active'), ('closed', 'Closed')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userproject',
            name='status',
            field=models.CharField(blank=True, choices=[('active', 'Active'), ('complete', 'Complete'), ('withdrawn', 'Withdrawn')], max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='usertask',
            name='status',
            field=models.CharField(blank=True, choices=[('active', 'Active'), ('complete', 'Complete'), ('withdrawn', 'Withdrawn')], max_length=12, null=True),
        ),
    ]
