# Generated by Django 2.1.7 on 2019-04-03 10:55

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0033_auto_20181214_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='testing_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.UserGroup'),
        ),
        migrations.AlterField(
            model_name='projecttask',
            name='external_system',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.ExternalSystem'),
        ),
        migrations.AlterField(
            model_name='projecttask',
            name='testing_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.UserGroup'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email_verification_token',
            field=models.UUIDField(default=uuid.UUID('c7907be4-edb8-4d86-ac58-0c6bf63a36e2'), editable=False, null=True),
        ),
    ]
