# Generated by Django 2.1.7 on 2019-04-03 10:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0034_auto_20190403_1055'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='country_code',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email_verification_token',
            field=models.UUIDField(default=uuid.UUID('102a489a-bcce-4dde-ba46-72e2cdda48f8'), editable=False, null=True),
        ),
    ]
