# Generated by Django 2.1.7 on 2019-04-18 15:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0035_auto_20190403_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='country_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email_verification_token',
            field=models.UUIDField(default=uuid.UUID('6382310e-62aa-4280-bb91-6d4af7aeef08'), editable=False, null=True),
        ),
    ]
