# Generated by Django 2.1.7 on 2019-08-09 11:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0037_auto_20190422_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='projecttask',
            name='base_url',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email_verification_token',
            field=models.UUIDField(default=uuid.UUID('4d76f0b9-c5e5-4324-8dbd-b780ae809ca9'), editable=False, null=True),
        ),
    ]
