# Generated by Django 3.0 on 2019-12-13 11:41

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0040_unique_index_for_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='projecttask',
            name='progress_info',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='usertask',
            name='progress_info',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='user',
            name='email_verification_token',
            field=models.UUIDField(default=uuid.UUID('5ab5f85f-da63-4cae-98fd-e355823a28e5'), editable=False, null=True),
        ),
    ]
