# Generated by Django 2.2.7 on 2020-01-10 10:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0042_auto_20191213_1210'),
    ]

    operations = [
        migrations.AddField(
            model_name='userproject',
            name='ext_user_project_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usertask',
            name='ext_user_task_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email_verification_token',
            field=models.UUIDField(default=uuid.UUID('f625070c-978b-430f-a6e4-0108f3c652d3'), editable=False, null=True),
        ),
    ]
