# Generated by Django 2.2.7 on 2020-01-14 10:47

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0042_auto_20191213_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projecttask',
            name='progress_info',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projecttask',
            name='progress_info_modified',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email_verification_token',
            field=models.UUIDField(default=uuid.UUID('7f9a19a3-2b0b-4b92-9f92-3071a2a6f7cb'), editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='usertask',
            name='progress_info',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
