# Generated by Django 2.2.7 on 2020-01-15 11:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0043_auto_20200114_1047'),
    ]

    operations = [
        migrations.AddField(
            model_name='userproject',
            name='ext_user_project_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usertask',
            name='ext_user_task_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email_verification_token',
            field=models.UUIDField(default=uuid.UUID('bf4f71b8-17d1-41da-912e-a5eefb80db42'), editable=False, null=True),
        ),
    ]
