# Generated by Django 2.2.7 on 2020-02-26 10:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0044_auto_20200115_1128'),
    ]

    operations = [
        migrations.AddField(
            model_name='externalsystem',
            name='display_method',
            field=models.CharField(blank=True, choices=[('redirect', 'Redirect'), ('iframe', 'iFrame')], max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email_verification_token',
            field=models.UUIDField(default=uuid.UUID('faaa9c53-b846-4be3-bffb-604d3b9f8ec1'), editable=False, null=True),
        ),
    ]
