# Generated by Django 2.2.7 on 2020-03-03 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0045_auto_20200226_1056'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email_address_verified',
        ),
        migrations.RemoveField(
            model_name='user',
            name='email_verification_expiry',
        ),
        migrations.RemoveField(
            model_name='user',
            name='email_verification_token',
        ),
    ]
