# Generated by Django 2.2.7 on 2020-03-26 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0046_auto_20200303_1457'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectgroupvisibility',
            options={'verbose_name_plural': 'Project group visibilities'},
        ),
        migrations.AlterModelOptions(
            name='projecttaskgroupvisibility',
            options={'verbose_name_plural': 'Project task group visibilities'},
        ),
    ]
