# Generated by Django 2.2.7 on 2020-04-06 17:52

from django.db import migrations, models


class Migration(migrations.Migration):
    """
    Applying this migration might lead to error:
    django.db.utils.NotSupportedError: cannot alter type of a column used by a view or rule

    If so, the workaround is to delete all database views, apply this migration, then recreate the views using the
    script in thiscovery-core
    """

    dependencies = [
        ('projects', '0047_auto_20200326_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='project',
            name='short_name',
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
