# Generated by Django 2.2.7 on 2020-04-06 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0047_auto_20200326_1205'),
    ]

    operations = [
        migrations.AddField(
            model_name='projecttask',
            name='user_specific_url',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usertask',
            name='url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
