# Generated by Django 2.2.7 on 2020-07-02 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0050_auto_20200418_1008'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userproject',
            old_name='ext_user_project_id',
            new_name='anon_project_specific_user_id',
        ),
        migrations.RenameField(
            model_name='usertask',
            old_name='ext_user_task_id',
            new_name='anon_user_task_id',
        ),
    ]
