# Generated by Django 2.2.7 on 2020-07-05 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0050_auto_20200418_1008'),
    ]

    operations = [
        migrations.AddField(
            model_name='userproject',
            name='anon_project_specific_user_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usertask',
            name='anon_user_task_id',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
