# Generated by Django 2.2.7 on 2020-07-02 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0051_auto_20200702_0927'),
    ]

    operations = [
        migrations.AddField(
            model_name='projecttask',
            name='anonymise_url',
            field=models.BooleanField(default=True),
        ),
    ]
