# Generated by Django 3.0 on 2020-11-04 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0052_projecttask_anonymise_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnonId',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anon_user_task_id', models.UUIDField()),
                ('anon_project_specific_user_id', models.UUIDField()),
                ('user_id', models.UUIDField()),
                ('email', models.CharField(max_length=100)),
                ('project_name', models.CharField(max_length=150)),
                ('project_id', models.UUIDField()),
                ('user_task_id', models.UUIDField()),
                ('project_task_id', models.UUIDField()),
                ('project_task_description', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'user_tasks_with_anon_ids',
                'managed': False,
            },
        ),
        migrations.AlterField(
            model_name='projecttask',
            name='base_url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
