# Generated by Django 2.2.7 on 2020-12-02 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0053_auto_20201104_1125'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='demo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usergroup',
            name='demo',
            field=models.BooleanField(default=False),
        ),
    ]
