# Generated by Django 3.1.4 on 2021-01-06 16:25
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0058_unique_usergroup_membership_trigger'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='description',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='projecttask',
            name='name',
            field=models.CharField(default='unnamed task', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projecttask',
            name='short_name',
            field=models.CharField(default='unnamed task', max_length=80),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='short_name',
            field=models.CharField(max_length=80),
        ),
    ]
